services:
  app_proxy:
    environment:
      APP_HOST: kraskus
      APP_PORT: 18401

  kraskus:
    image: ghcr.io/kraskuscrypto/kraskus-zec-solo@sha256:f8a49a7eb6d8215d3163f08f0bdb4c354962ea2799e3388d6f6100c251f1f811
    restart: unless-stopped

    depends_on:
      - zebra

    environment:
      KRASKUS_BASE: /data
      KRASKUS_PACKAGED_MODE: "1"

      KRASKUS_ZEBRA_RPC_URL: http://zebra:18232
      KRASKUS_ZEBRA_COOKIE_FILE: /zebra/.cookie

      KRASKUS_MINER_ADDRESS_FILE: /kraskus-config/miner-address
      KRASKUS_NETWORK_FILE: /kraskus-config/network

      KRASKUS_STRATUM_HOST: 0.0.0.0
      KRASKUS_STRATUM_PORT: 3335

      KRASKUS_STRATUM_HEALTH_HOST: 127.0.0.1
      KRASKUS_STRATUM_HEALTH_PORT: 18402
      KRASKUS_STRATUM_STATUS_URL: http://127.0.0.1:18402/status

    volumes:
      - ${APP_DATA_DIR}/kraskus:/data
      - ${APP_DATA_DIR}/zebra:/zebra:ro
      - ${APP_DATA_DIR}/config:/kraskus-config

    ports:
      - "3335:3335"

    security_opt:
      - no-new-privileges:true

  zebra:
    image: ghcr.io/kraskuscrypto/kraskus-zebra@sha256:abbbddd84563023df621f1eecceeb816da5c2951d9b60718133f131e1341c6d0
    restart: unless-stopped

    environment:
      ZEBRA_NETWORK__LISTEN_ADDR: 0.0.0.0:18233

      ZEBRA_RPC__LISTEN_ADDR: 0.0.0.0:18232
      ZEBRA_RPC__COOKIE_DIR: /home/zebra/.cache/zebra

      ZEBRA_STATE__CACHE_DIR: /home/zebra/.cache/zebra

      KRASKUS_MINER_ADDRESS_FILE: /kraskus-config/miner-address
      KRASKUS_NETWORK_FILE: /kraskus-config/network

    volumes:
      - ${APP_DATA_DIR}/zebra:/home/zebra/.cache/zebra
      - ${APP_DATA_DIR}/config:/kraskus-config:ro

    security_opt:
      - no-new-privileges:true
