services:

  app_proxy:
    environment:
      APP_HOST: kraskus
      APP_PORT: 18401

  kraskus:
    image: ghcr.io/kraskuscrypto/kraskus-zec-solo@sha256:ea132222a7a3ca687a3abdf56b5b352c2d3b17e911d1ad5ec59de5308a9a2f77
    restart: unless-stopped

    depends_on:
      - zebra

    environment:
      KRASKUS_BASE: /data

      KRASKUS_ZEBRA_CONTAINER: kraskus-zec-solo-zebra
      KRASKUS_ZEBRA_RPC_URL: http://zebra:18232
      KRASKUS_ZEBRA_COOKIE_FILE: /zebra/.cookie

      KRASKUS_STRATUM_HOST: 0.0.0.0
      KRASKUS_STRATUM_PORT: 3335

      KRASKUS_STRATUM_HEALTH_HOST: 127.0.0.1
      KRASKUS_STRATUM_HEALTH_PORT: 18402

      KRASKUS_STRATUM_STATUS_URL: http://127.0.0.1:18402/status

    volumes:
      - ${APP_DATA_DIR}/kraskus:/data
      - ${APP_DATA_DIR}/zebra:/zebra:ro
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "3335:3335"

    security_opt:
      - no-new-privileges:true

  zebra:
    container_name: kraskus-zec-solo-zebra
    image: zfnd/zebra@sha256:bb2a6029db277ee3a10e951dcc0ddd36b4cbcbe0fad684746d695ee21d53fde2
    restart: unless-stopped

    environment:
      ZEBRA_NETWORK__NETWORK: Testnet
      ZEBRA_RPC__LISTEN_ADDR: 0.0.0.0:18232

    volumes:
      - ${APP_DATA_DIR}/zebra:/home/zebra/.cache/zebra

    security_opt:
      - no-new-privileges:true
